title: David Rodríguez | Fullstack Developer
description: I am Ruby on Rails and React developer.
url: https://portfolio-jekyll-denzilrh90.vercel.app
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
  - vendor
